# Generated by Django 4.0.6 on 2022-07-19 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_type_author_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="type",
            name="user",
        ),
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="Age",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
