# Generated by Django 4.0.6 on 2022-07-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_remove_type_user_alter_author_id_alter_poem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poem",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.author"
            ),
        ),
    ]
