name: django

on: [push]

env:
  DJANGO_DB: ${{ secrets.DJANGO_DB }}
  DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create migrations
        run: |
          cd backend/core/
          python manage.py migrate
      - name: Run tests
        run: |
          cd backend/core/
          python pytest
